activitiesEvents = [
    {"id_event": 1, "id_category": 1, "Description": "Embark on a hunt through thrift stores to find unique treasures.", "TITLE": "Exploring Thrift Stores"},
    {"id_event": 2, "id_category": 2, "Description": "Enjoy socializing and swapping clothes with like-minded individuals over drinks.", "TITLE": "Sip, Swap, and Socialize"},
    {"id_event": 3, "id_category": 3, "Description": "Learn the art of upcycling and transform old garments into new, stylish pieces.", "TITLE": "Upcycle Mastery"},
    {"id_event": 4, "id_category": 4, "Description": "Experience a runway show featuring vintage fashion and second-hand clothing.", "TITLE": "Vintage Vogue"},
    {"id_event": 5, "id_category": 1, "Description": "Participate in a hands-on session where experts style outfits using second-hand clothes.", "TITLE": "Style Workshop"},
    {"id_event": 6, "id_category": 2, "Description": "Embark on a challenge to visit multiple thrift stores and discover hidden gems.", "TITLE": "Thrift Store Treasure Hunt"},
    {"id_event": 7, "id_category": 1, "Description": "Get creative by customizing and personalizing second-hand clothing with DIY techniques.", "TITLE": "Creative Customization with DIY Chic"},
    {"id_event": 8, "id_category": 3, "Description": "Engage in a panel discussion exploring sustainable practices in the fashion industry.", "TITLE": "Fashion's Eco-Friendly Future"},
    {"id_event": 9, "id_category": 3, "Description": "Network with eco-conscious fashion enthusiasts and professionals in a social setting.", "TITLE": "EcoStyle Mixer"},
    {"id_event": 10, "id_category": 3, "Description": "Explore a pop-up market featuring pre-loved items from various sellers.", "TITLE": "Pre-Loved Finds Galore"},
    {"id_event": 11, "id_category": 4, "Description": "Join a community-wide scavenger hunt to discover hidden thrift store gems.", "TITLE": "Community Scavenger Hunt"},
    {"id_event": 12, "id_category": 4, "Description": "Sip on your favorite beverages while swapping clothes and stories with fellow fashion enthusiasts.", "TITLE": "Sip & Swap"},
    {"id_event": 13, "id_category": 2, "Description": "Unlock the secrets of upcycling in this hands-on workshop, turning old garments into fashion masterpieces.", "TITLE": "The Secrets of Upcycling"},
    {"id_event": 14, "id_category": 1, "Description": "Immerse yourself in the glamour of vintage fashion with a showcase of unique and timeless pieces.", "TITLE": "Vintage is forever"},
    {"id_event": 15, "id_category": 1, "Description": "Witness expert stylists creating stunning looks using second-hand clothes in this interactive session.", "TITLE": "Witness the Fashion Alchemy"},
    {"id_event": 1, "id_category": 1, "Description": "Challenge yourself to visit multiple thrift stores and complete exciting tasks along the way.", "TITLE": "Thrift Store Adventure"},
    {"id_event": 2, "id_category": 1, "Description": "Express your creativity by customizing and personalizing second-hand clothing in a fun DIY workshop.", "TITLE": "DIY workshop - Turin Session"},
    {"id_event": 3, "id_category": 3, "Description": "Gain insights into sustainable fashion practices through a thought-provoking panel discussion.", "TITLE": "Insights from a Thought-Provoking Panel Discussion"},
    {"id_event": 4, "id_category": 4, "Description": "Expand your network within the eco-friendly fashion community at this casual and informative mixer.", "TITLE": "EcoStyle Connect"},
    {"id_event": 5, "id_category": 2, "Description": "Browse and shop from a diverse range of pre-loved items at a pop-up market dedicated to sustainable fashion.", "TITLE": "The Sustainability of fashion!"},
]